### ISSUE TITLE
GNS Per-Frame Inference Time

### ISSUE THREAD

**Issue by iSach** [tum-pbs/DMCF#18]
Hello,

I am currently working on reproducing your results, which was easy thanks to your script, and the results of GNS, using their code.

I am trying to analyze inference time, and see that in your work, you managed to compute inference times for GNS, I guess using their implementation? How did you modify their code to measure this time? I am really not used to TensorFlow, especially v1, and I am unable to track the inference time.

I am asking you directly here because the GNS team is not answering. This would greatly help me in having consistent results (inference time measured on the same hardware).

Thanks a lot and best regards,
Sacha Lewin.

**Comment by Prantl** [comment]
Hi,

Unfortunately I can't remember exactly, but I'm pretty sure I had to change the GNS code for it. I think I had measured the time that rollout_estimator.predict needs in the eval_rollout in the train.py script. I measured the complete time and divided it by the number of time steps to get the average time. Make sure that the code only does the prediction and no additional evaluations or I/O functions by removing the corresponding functions (I think it does some evaluations, the setup seems to be in get_rollout_estimator_fn). You also need to make sure that the timing function is really synchronized with the run, since the tf run can run on the GPU, but I'm not sure if there isn't some extra work to do there. Maybe check the TF documentation to see if there is info on this.
For a more reliable answer, you will unfortunately have to hope for an answer from the GNS team. 

Best regards,
Lukas

**Comment by iSach** [comment]
Hello Lukas,

Thank you so much for your fast and complete answer. I will attempt what you mentioned as I haven't tried yet to remove those parts. It's indeed hard to get it synced, but I will try again!

Thanks again and best regards,
Sacha Lewin
